### Register API
# This request is used to create a new user account
POST http://localhost:9080/register HTTP/1.1
Content-Type: application/json

{
    "username": "anjali2",
    "password": "password123",
    "email": "anjali2@gmail.com",
    "name": "Anjali"
} 

### Login API
# This request is used to authenticate user and return a token

POST http://localhost:9080/login HTTP/1.1
Content-Type: application/json

{
    "email": "anjali2@gmail.com",
     "password": "password123",
    
} 

