### Register API
# This request is used to create a new user account
POST http://localhost:9090/user/register HTTP/1.1
Content-Type: application/json

# {
#     "username": "anjali2",
#     "password": "password123",
#     "email": "anjali2@gmail.com",
#     "name": "Anjali"
# }

{
    "username": "rahul1",
    "password": "a",
    "email": "rahul@gmail.com",
    "name": "Rahul"
}

### Login API
# This request is used to authenticate user and return a token

POST http://localhost:9090/user/login HTTP/1.1
Content-Type: application/json

{
    "email": "anjali2@gmail.com",
     "password": "password123"
    
} 


###
POST http://localhost:9090/user/login HTTP/1.1
Content-Type: application/json

{
    "email": "rahul@gmail.com",
     "password": "a"
    
} 


### 

GET http://localhost:9090/user/get_user_and_profile HTTP/1.1
Content-Type: application/json

{
    "token" : "360e553d2305701cd1ca62a12db67f1be21817e31b035d09698edd612edf0a61"
    
} 


###

POST http://localhost:9090/user/update_profile_data HTTP/1.1
Content-Type: application/json

{
    "token" : "3bd652920740b37df6f26463d6acf27ce7b7748d53b45cfdb6533278d5498317",
    "bio" : "Software Engineer",
    "currentPost" : "CTO",
    "pastwork" : [
        {
            "company": "Microsoft",
            "position": "CTO",
            "years" : "2+"
        }
    ],
    "education" : [
        {
            "school" : "IIT",
            "degree" : "B.Tech",
            "fieldofStudy" : "2015-2019"
        }
    ]
} 


###

GET http://localhost:9090/user/get_all_users



